export {
  AI_ASSISTANT_UUID,
  AI_ASSISTANT_EMAIL,
  AI_ASSISTANT_FIRST_NAME,
  AI_ASSISTANT_LAST_NAME,
  AI_ASSISTANT_DISPLAY_NAME,
  AI_ASSISTANT_PROFILE_PICTURE_URL,
  AI_DIRECTIVE_REGEX,
  AI_SEARCH_DIRECTIVE_REGEX,
  AI_STATUS_EVENT,
  AI_STREAM_EVENT,
  AI_METRICS_EVENT,
  AI_HISTORY_LIMIT,
} from "../../AI/backend/constants.js";
